name: note_pad
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.11.0
  path_provider: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  watcher: ^1.1.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Hind Siliguri
      fonts:
        - asset: lib/res/font/HindSiliguri-Regular.ttf
        - asset: lib/res/font/HindSiliguri-Medium.ttf
          style: normal
          weight: 700
  assets:
    - lib/res/images/file.png
